package main

//check test directory
import (
	"fmt"
	"os"
	"time"

	"gopkg.in/yaml.v2"

	"gitlab.lrz.de/ga53lis/PASSA/ymlparser"
)

const ymlReference = "passa-states.yml"
const ymlTest = "test/passa-states-test.yml"

func main() {
	c := ymlparser.ParseStatesfile(ymlReference)
	currentTime := time.Now()

	addedMinutes := [4]int{15, 20, 25, 30} //Constant

	for idx := range c.States {
		timein := currentTime.Local().Add(time.Minute * time.Duration(addedMinutes[idx]))
		c.States[idx].Time = timein.Format(ymlparser.TimeLayout)
	}
	fmt.Printf("%v", c)

	ymlByte, err := yaml.Marshal(&c)
	check(err)
	f, err := os.Create(ymlTest)
	check(err)
	defer f.Close()

	f.WriteString("# Generated by internal/generator/ymlGenerator.go\n---\n")
	f.Write(ymlByte)
}

func check(err error) {
	if err != nil {
		panic(err)
	}
}
